services:
  frontend:
    image: arsen00531/totweb-frontend
    container_name: frontend
    build:
      context: ../../client/totweb-frontend/.
    ports:
      - 8081:80
    expose:
      - 80
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  backend:
    image: arsen00531/totweb-backend
    container_name: backend
    env_file:
      - .production.env
    build:
      context: .
    volumes:
      - /backend/node_modules
    ports:
      - 5001:5001
      - 9229:9229
    command: npm run start:prod
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: totweb-postgres
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
