services:
  frontend:
    container_name: frontend
    build:
      context: ../../client/totweb-frontend/.
    ports:
      - 8080:80
    expose:
      - 80
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - app
  backend:
    container_name: backend
    env_file:
      - .production.env
    build:
      context: .
    volumes:
      - /backend/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:prod
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  # documentation:
  #   container_name: documentation
  #   env_file:
  #     - .production.env
  #   build:
  #     context: /home/arsen00531/server/connect-birga-docs/.
  #   volumes:
  #     - /home/arsen00531/server/connect-birga-docs/dist/src/uploads:/app/backend/dist/src/uploads
  #     - /app/backend/node_modules
  #   ports:
  #     - 5060:5000
  #     - 9230:9229
  #   command: npm run start:prod
  #   restart: always

volumes:
  pgdata:
